version: '3'

services:
  database:
    image: postgres:16.3
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  # for prod only
  # https://github.com/nodejs/docker-node/blob/main/README.md#how-to-use-this-image
  app:
    # dockerfile unused for now
    # TODO: use dockerfile because dependencies exist, I have not deployed this to prod yet.
    # build: .
    image: node:18.20.4-bookworm-slim
    user: node
    working_dir: /home/node/app
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - NODE_ENV=production
    command: "npm start"
    volumes:
      - ./:/home/node/app
    profiles:
  dev:
    # dockerfile unused for now
    # TODO: use dockerfile because dependencies exist, I have not deployed this to prod yet.
    # build: .
    image: node:18.20.4-bookworm-slim
    user: node
    working_dir: /home/node/app
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - NODE_ENV=development
    command: "npm start"
    volumes:
      - ./:/home/node/app:ro # TODO this may cause issues?
    profiles: ["dev"]